### ISSUE TITLE
Some question about the results on miniImageNet

### ISSUE THREAD

**Issue by skingorz** [Yikai-Wang/ICI-FSL#17] opened 2022-04-07 15:45 UTC
Thank you for you excellent  work! However, when I try to reimplement the  5way-1shot result  on miniImageNet, the performance is about 3% lower than that in the paper. I only changed the [unlabel number](https://github.com/Yikai-Wang/ICI-FSL/blob/master/V2-TPAMI/config.py#L72) to  30 according the paper.  Is there anything else that needs to be modified?

**Comment by Yikai-Wang** [comment] 2022-04-07 23:12
Please provide more details to help me locate the problem, like the package environment, the running command you used, and the full output information.

Besides, please note that the termination condition is different when we run on different settings, as we said in the experiment part of the paper. Our implementation instead runs until all the unlabeled data are selected for simplicity, while the result is selected based on the termination condition used in our paper.

**Comment by Yikai-Wang** [comment] 2022-05-07 05:14
The issue is closed as no further information provided for a long time.

**Closed as completed by Yikai-Wang** 2022-05-07 05:14 UTC
